# Config for https://app.pagescms.org/matrixik/dobek.pro/master/settings

media:
  input: content/posts
  output: /content/posts
  categories: [ image ]

content:
  - name: posts
    label: Posty
    type: collection
    path: content/posts
    format: toml-frontmatter
    filename: "{year}-{month}-{day}-{primary}/index.md"
    view:
      fields: [title, date, draft]
    fields:
        - name: title
          label: Title
          type: string
        - name: slug
          label: Slug
          type: string
        - name: description
          label: Description
          type: string
        - name: date
          label: Date
          type: date
        - name: lastmod
          label: Last modification date
          type: date
        - name: authors
          label: Authors
          hidden: true
          type: string
          list:
            min: 1
          default: 
            - matrixik
        - name: categories
          label: Categories
          type: string
          list: true
          options:
            values:
              - DevOps
              - Programowanie
              - Technologia
        - name: tags
          label: Tags
          type: string
          list:
            min: 1
        - name: draft
          label: draft
          type: boolean
          default: true
        - name: body
          label: Body
          type: rich-text

  - name: o-mnie
    label: O mnie
    type: file
    path: content/pages/o-mnie.md
    fields:
      - {name: title, label: Title, type: string}
      - {name: description, label: Description, type: string}
      - name: type
        label: Page type
        type: string
        default: page
      - name: menu
        label: Menu
        type: string
        default: main
        hidden: true
      - name: weight
        label: Page weight
        type: number
      - name: comments
        label: Show comments
        type: boolean
      - {name: body, label: Body, type: rich-text}