baseURL = "https://www.dobek.pro"
title = "Zrzut myśli"
# for smart copyright line, leave this blank and check [params.copyright]
copyright = ""

theme = "minimo"

disqusShortname = "dobek-pro"
googleAnalytics = "UA-107708586-1"

Paginate = 10
rssLimit = 15
preserveTaxonomyNames = true

enableRobotsTXT = true # generate robots.txt

# Syntax Highlighting ( https://gohugo.io/content-management/syntax-highlighting/ )
pygmentsCodefences = true

defaultContentLanguage = "pl"

enableEmoji = true

[outputFormats.RSS]
mediatype = "application/rss"
baseName = "rss"

[params.info]
description = "Trochę więcej wiedzy"
title404 = "Tej wiedzy jeszcze nie mam"

[params.assets]
favicon = "favicon.ico"
customCSS = ["css/custom.css"]
customJS = ["js/custom.js"]
gopher = "" # used in 404 template ( Generator: https://gopherize.me )

[params.copyright]
prefix = ""
holder = "Dobrosław Żybort"
startYear = "2017"
suffix = ""

[params.settings]
# date & time format: https://golang.org/pkg/time/
dateFormat = "2006-01-02"
listDateFormat = "2006-01-02"
hideEntryNavigation = ["page"] # boolean / array of sections
hideSocialMenu = false
showReadingTime = false

[params.opengraph.facebook]
admins = [] # array of Facebook IDs
appID = ""
pageID = ""

[params.opengraph.twitter]
page = "" # Twitter page username

[params.seo]
# Title Separator: - – — · • * ⋆ | ~ « » < >
titleSeparator = "•"

[params.social]
codepen = ""
email = "matrixik@gmail.com"
facebook = ""
github = "matrixik"
instagram = ""
twitter = "matrixik"
linkedin = "dobroslaw-zybort"

[params.social.config]
platforms = ["email", "github", "linkedin", "twitter"]

[taxonomies]
author = "authors"
category = "categories"
tag = "tags"

[permalinks]
page = "/:slug/"
blog = "/:year-:month-:slug/"

[[menu.main]]
name = "Repo"
weight = -10
identifier = "repository"
url = "https://github.com/matrixik/dobek.pro"

[blackfriday]
hrefTargetBlank = true

[languages]
# edit this block for your own language
[languages.pl]
lang = "pl"
languageName = "Polski"
weight = 1

