title = "Zrzut myśli"
baseURL = "https://www.dobek.pro/"
languageCode = "pl-PL"
buildDrafts = false
canonifyURLs = true

theme = "cocoa-eh"
contentDir = "content"
layoutDir = "layouts"
publishDir = "public"

[taxonomies]
category = "kategorie"
tag = "tagi"

[params]
logofile = "img/dz_0280x0280.jpg"
author = "Dobrosław Żybort"
