[build]
publish = "public"
command = "make all"

[build.environment]
HUGO_VERSION = "0.41"

[context.production.environment]
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.deploy-preview]
command = "make netlify"

[context.deploy-preview.environment]
HUGO_GOOGLEANALYTICS = "dev"

[context.branch-deploy]
command = "make netlify"

[context.branch-deploy.environment]
HUGO_GOOGLEANALYTICS = "dev"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"
